### ISSUE TITLE
problem from installation

### ISSUE THREAD

**Issue by jjhesk** [callistachang/merkletreepy#1]
```

Collecting merkletreepy
  Downloading merkletreepy-0.0.4.tar.gz (3.8 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
      Traceback (most recent call last):
        File "/Users/hesdx/Library/Python/3.8/lib/python/site-packages/keyring/backend.py", line 198, in _load_plugins
          init_func = ep.load()
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/metadata.py", line 77, in load
          module = import_module(match.group('module'))
        File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
      ModuleNotFoundError: No module named 'keyring.backends.macOS'
      Looking in indexes: https://pypi.python.org/simple
      Collecting setuptools>=42
        Downloading setuptools-62.1.0-py3-none-any.whl (1.1 MB)
           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 2.8 MB/s eta 0:00:00
      Collecting wheel
        Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
      WARNING: Ignoring invalid distribution -ntp (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages)
      Installing collected packages: wheel, setuptools
      ERROR: Cannot set --home and --prefix together
      WARNING: Ignoring invalid distribution -ntp (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
WARNING: Ignoring invalid distribution -ntp (/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages)
```

**Comment by callistachang** [comment]
https://github.com/jaraco/keyring/issues/511 does this help? my bad, I don't have a macOS machine to test this!

**Comment by callistachang** [comment]
Closing this because I now have a MacOS machine and it seems to be working fine. Feel free to reopen this issue if you meet any other problems!

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/34191886/204698117-6b7d507f-dbe7-422b-8664-0dae2df3b795.png">
